# Generated by Django 6.0 on 2025-12-22 07:49

from django.db import migrations

from django.contrib.auth.models import User
from general.models import UserProfile

def create_user_profiles_for_old_users(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        try:
            user.userprofile
        except UserProfile.DoesNotExist:
            UserProfile.objects.create(user = user)
class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_alter_userprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RunPython(create_user_profiles_for_old_users)
    ]
