# Generated by Django 6.0 on 2025-12-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_auto_20251222_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='type',
            field=models.TextField(choices=[('reviewer', 'рецензер'), ('editor', 'редактор')], null=True),
        ),
    ]
