# Generated by Django 6.0 on 2026-01-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_userprofile_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_objects', 'Может создавать объекты'), ('can_read_objects', 'Может просматривать информацию об объектах'), ('can_update_objects', 'Может обновлять объекты'), ('can_delete_objects', 'Может удалять объекты'), ('can_filter_objects', 'Может фильтровать объекты')]},
        ),
    ]
