# Generated by Django 6.0 on 2026-01-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_create_objects', 'Может создавать объекты'), ('can_read_objects', 'Может просматривать информацию об объектах'), ('can_update_objects', 'Может обновлять объекты'), ('can_delete_objects', 'Может удалять объекты'), ('can_create_rating_movie', 'Может ставить свою оценку кино'), ('can_update_rating_movie', 'Может обновлять свою оценку кино'), ('can_delete_rating_movie', 'Может удалять свою оценку кино')]},
        ),
    ]
