# Generated by Django 6.0 on 2026-01-13 14:45
import pyotp
from django.db import migrations, models

def fill_totp_field(apps, schema_editor):
    UserProfile = apps.get_model('general', 'UserProfile')
    for u in UserProfile.objects.all():
        u.totp_key = pyotp.random_base32()
        u.save()

class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_alter_userprofile_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='totp_key',
            field=models.TextField(null=True),
        ),
        migrations.RunPython(fill_totp_field)
    ]
