# Generated by Django 6.0 on 2026-02-17 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_userprofile_totp_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
