# Generated by Django 6.0 on 2025-12-22 15:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_ratingmovie_user_alter_director_date_of_birth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingmovie',
            unique_together={('movie', 'user')},
        ),
    ]
