# Generated by Django 6.0 on 2025-12-29 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_ratingmovie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='picture',
            field=models.ImageField(null=True, upload_to='movies', verbose_name='Изображение'),
        ),
    ]
