# Generated by Django 6.0 on 2025-12-29 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='picture',
            field=models.ImageField(null=True, upload_to='directors', verbose_name='Изображение'),
        ),
    ]
