# Generated by Django 6.0 on 2026-01-12 06:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_director_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='year_of_release',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1895), django.core.validators.MaxValueValidator(2026)], verbose_name='Год выхода'),
        ),
    ]
